/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.beans.PropertyVetoException;

/**
 *
 * @author PC
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        //initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        dskPrinc.removeAll();
        dskPrinc.add(menuPrincipal);
        //MenuPrincipal menuPrincipal = new FrmMenuPrincipal();
        try{
            menuPrincipal.setMaximum(true);
        }
        catch(PropertyVetoException ex){
            ex.printStackTrace();
        }
        menuPrincipal.setVisible(true);
        menuPrincipal.repaint();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPrinc = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opcMenuPrincipal = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opcModuloAlta = new javax.swing.JMenuItem();
        opcModuloJornada = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPrincLayout = new javax.swing.GroupLayout(dskPrinc);
        dskPrinc.setLayout(dskPrincLayout);
        dskPrincLayout.setHorizontalGroup(
            dskPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 972, Short.MAX_VALUE)
        );
        dskPrincLayout.setVerticalGroup(
            dskPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        jMenu1.setText("Menú Principal");

        opcMenuPrincipal.setText("Menú Principal");
        opcMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcMenuPrincipalActionPerformed(evt);
            }
        });
        jMenu1.add(opcMenuPrincipal);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Otros menús");

        opcModuloAlta.setText("Módulo Asesores");
        opcModuloAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcModuloAltaActionPerformed(evt);
            }
        });
        jMenu2.add(opcModuloAlta);

        opcModuloJornada.setText("Módulo Jornada");
        opcModuloJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcModuloJornadaActionPerformed(evt);
            }
        });
        jMenu2.add(opcModuloJornada);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 972, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dskPrinc))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dskPrinc))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcMenuPrincipalActionPerformed
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        dskPrinc.add(menuPrincipal);
        
        try{
            menuPrincipal.setMaximum(true);
        }
        catch(PropertyVetoException ex){
            ex.printStackTrace();
        }
        
        menuPrincipal.setVisible(true);
        menuPrincipal.repaint();
        
        repaint();
    }//GEN-LAST:event_opcMenuPrincipalActionPerformed

    private void opcModuloAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcModuloAltaActionPerformed
        ModuloAltaAsesores menuAltaAsesores = new ModuloAltaAsesores();
        dskPrinc.add(menuAltaAsesores);
        
        try{
            menuAltaAsesores.setMaximum(true);
        }
        catch(PropertyVetoException ex){
            ex.printStackTrace();
        }
        
        menuAltaAsesores.setVisible(true);
        menuAltaAsesores.repaint();
        
        repaint();
    }//GEN-LAST:event_opcModuloAltaActionPerformed

    private void opcModuloJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcModuloJornadaActionPerformed
        ModuloJornada menuJornada = new ModuloJornada();
        dskPrinc.add(menuJornada);
        
        try{
            menuJornada.setMaximum(true);
        }
        catch(PropertyVetoException ex){
            ex.printStackTrace();
        }
        
        menuJornada.setVisible(true);
        menuJornada.repaint();
        
        repaint();
    }//GEN-LAST:event_opcModuloJornadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPrinc;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opcMenuPrincipal;
    private javax.swing.JMenuItem opcModuloAlta;
    private javax.swing.JMenuItem opcModuloJornada;
    // End of variables declaration//GEN-END:variables
}
